### ISSUE TITLE
Shift Maven and SpringBoot artifacts to /dev; document changes for new versions of Spring Boot

### ISSUE THREAD

**Issue by wtcox** [EnergyMashupLab/NIST-CTS-Agents#26]
Need to reduce clutter at top level of archive.j Seems that most is caused by Maven files and directories.

**Comment by wtcox** [comment]
Still pending post mid-term.

**Comment by wtcox** [comment]
Include a README on changes (if any) needed for future versions of Spring Boot.

**Comment by KaranShah197** [comment]
It has been done and code is now in master branch.
