### ISSUE TITLE
Use Travis CI or Jenkins for automatic commit verification and builds

### ISSUE THREAD

**Issue by KaranShah197** [EnergyMashupLab/NIST-CTS-Agents#40]

**Comment by wtcox** [comment]
Help test the environment after pull of code.
In sprint4 branch now. TravisCI.yml - please mention in "how to develop"

**Comment by wtcox** [comment]
Karan - implemented not committed - needs unit test fixes first.

**Comment by KaranShah197** [comment]
Added MD file for the same
